---
title: "Networks & Rasters"
author: "Matt Khinda"
date: "10/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load libraries, include = FALSE}
options(java.parameters = "-Xmx4G")

library(r5r)
library(sf)
library(osmextract)
library(tidyverse)
library(ggthemes)
library(ggspatial)
library(tigris)
library(wesanderson)
library(tidytransit)
library(stars)
```

```{r gtfs data}
dir.create("networks")

download.file("https://transitfeeds.com/p/mbta/64/latest/download", file.path("networks","MBTAgtfs.zip"), mode = "wb", quiet=TRUE)
```

```{r street data}
Mass_file <- oe_match("us/massachusetts")

Mass_streets <- oe_read(Mass_file$url, 
                   provider = "openstreetmap_fr", 
                   download_directory = "networks", 
                   layer = "lines", 
                   quiet = TRUE) %>%
  filter(!is.na(highway))

```

```{r plot 1, echo=FALSE}
ggplot(Mass_streets) +
  geom_sf()
```

```{r chelsea boudaries,echo=FALSE}
Chelsea_tigris <- places("Massachusetts")%>%
  filter(NAME == "Chelsea") %>%
  st_transform(crs = st_crs(Mass_streets))

ggplot(Chelsea_tigris) +
  geom_sf()
```

```{r clipping streets, echo=FALSE}
MA_state_plane <- "+proj=lcc +lat_1=41.71666666666667 +lat_2=42.68333333333333 +lat_0=41 +lon_0=-71.5 +x_0=200000 +y_0=750000 +ellps=GRS80 +units=m +no_defs"

Chelsea_streets <- Mass_streets[Chelsea_tigris,]

##Removing MA data to speed up git pushes
rm(Mass_file, Mass_streets)

ggplot() +
  geom_sf(data = Chelsea_tigris, fill = "gray", color = NA) +
  geom_sf(data = Chelsea_streets) +
  coord_sf(crs = MA_state_plane)
  theme_void()

```

```{r grid, echo=FALSE}
grid <- st_sf(st_make_grid(Chelsea_tigris, square = FALSE,
                           n = c(100, 100),
                           what = "polygons")) %>% 
  st_filter(Chelsea_tigris)

colnames(grid) <- "geometry"
st_geometry(grid) <- "geometry"

grid <- grid %>% 
  mutate(id = seq(1, length(grid$geometry), by = 1))

grid_points <- st_centroid(grid)

ggplot() +
  geom_sf(data = grid)
```


```{r transit stops}
Mass_transit <- read_gtfs(file.path("networks", "MBTAgtfs.zip"))

#filter out only Chelsea stops so it won't return NAs for lat and lon
Chelsea_transit_stops <- subset(Mass_transit$stops, Mass_transit$stops$municipality == "Chelsea")

transit_stops <- st_as_sf(Chelsea_transit_stops, 
                          coords = c("stop_lon", "stop_lat"),
                          crs =st_crs(grid))

ggplot() +
  geom_sf(data = grid, fill = "gray", color = NA) +
  geom_sf(data = transit_stops, fill = "blue")

transit_grid <- grid %>%
  mutate(num_stops = lengths(st_covers(grid, transit_stops)))

transit_points <- st_centroid(transit_grid)

ggplot(transit_points) +
  geom_sf(aes(color = as.character(num_stops))) +
  scale_color_manual(values = c("lightgray", "green", "blue", "darkblue", "purple"), 
                    name = "Number of\ntransit stops") +
  theme_void()
```

```{r accessibility, echo = FALSE}
r5r_core <- setup_r5("networks", verbose = FALSE)

transit_access <- accessibility(r5r_core,
                        origins = transit_points,
                        destinations = transit_points,
                        mode = "WALK",
                        opportunities_colname = "num_stops",
                        decay_function = "step",
                        cutoffs = 11,
                        departure_datetime = as.POSIXct("15-11-2021 14:00:00",
                                 format = "%d-%m-%Y %H:%M:%S"),
                        max_walk_dist = 500,
                        time_window = 60,
                        percentiles = 50,
                        verbose = FALSE) %>%
  mutate(id = as.numeric(from_id)) %>%
  merge(grid)

st_geometry(transit_access) <- "geometry"

ggplot(transit_access) +
  geom_sf(aes(fill = accessibility), color = NA) +
  scale_fill_viridis_c(name = "Transit stops\nwithin 10-minutes\nwalk",option = "cividis") +
  coord_sf(crs = MA_state_plane) +
  theme_void()

```
```{r transit access 2}
transit_access2 <- accessibility(r5r_core,
                        origins = transit_points,
                        destinations = transit_points,
                        mode = "WALK",
                        opportunities_colname = "num_stops",
                        decay_function = "exponential",
                        cutoffs = 5,
                        departure_datetime = as.POSIXct("15-11-2021 14:00:00",
                                 format = "%d-%m-%Y %H:%M:%S"),
                        max_walk_dist = 500,
                        time_window = 60,
                        percentiles = 50,
                        verbose = FALSE) %>%
  mutate(id = as.numeric(from_id)) %>%
  merge(grid)

st_geometry(transit_access2) <- "geometry"

ggplot(transit_access2) +
  geom_sf(aes(fill = accessibility), color = NA) +
  scale_fill_viridis_c(name = "Accessiblity score", option = "magma") +
  coord_sf(crs = MA_state_plane) +
  theme_void()

st_write(transit_access2, 'Chelsea_access.geojson', append=FALSE, quiet=TRUE )

```

```{r stop core, include=FALSE}
stop_r5(r5r_core)
```

```{r access raster}
access_poly <- st_read("Chelsea_access.geojson", quiet=TRUE)

access_raster <- st_rasterize(access_poly["accessibility"], 
                              nx = 100, ny = 100)

ggplot(Chelsea_streets) +
  geom_stars(data = access_raster) +
  geom_sf(color = "white", alpha = 0.2) +
  coord_sf(crs = st_crs(grid)) +
  scale_fill_viridis_c(na.value = NA, 
                       option="mako",
                       name = "Pedestrian access\nto transit stops") +
  theme_void()
```
